name: CI Build & Test

on:
  push:
    branches:
      - '**'       # su qualsiasi push (puoi limitare a dev, feature/*, ecc)
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'   # usa la versione Node che vuoi

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build
